### ISSUE TITLE
Augmentor.jl

### ISSUE THREAD

**Issue by AriMKatz** [FluxML/FastAI.jl#68]
Is this helpful? https://github.com/Evizero/Augmentor.jl

**Comment by lorenzoh** [comment]
It greatly inspired DataAugmentation.jl, but had some design limitations which led me to develop a new library. Namely, it would have been hard to integrate data beside images like keypoints due to how random state is handled. But DataAugmentation.jl took a lot of ideas from it, like how to compose affine transformations.
