### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by jph00** [FluxML/FastAI.jl#7]
@opus111 I just wanted to leave a note to say thanks for working on this. Please let me know if I can help in any way. You might be interested in checking out SwiftAI, which uses a functional approach to creating a fastai-like with little if any mutation:

https://github.com/fastai/swiftai

We have a discord here if you want to chat in real-time about anything:

https://discord.com/invite/YKrxeNn

If this project gets popular I'd be happy to create a forum category for it if that would be helpful.

**Comment by sapal6** [comment]
@jph00 Thank you for the invite to the discord.

**Comment by opus111** [comment]
Wow!  Thank you Jeremy.  This is a great honor!  I am a huge fan of your classes and work :-D

Yes please.  We would love to join your discord, and, as much as possible, unify the Julia FastAI design with Swift.

Our goal is to encourage ML projects in Julia by providing an environment that is more powerful and flexible than Python, while also being familiar to developers.  FastAI is a great way to do this :-D

Our main concern is making bad design choices because we were unaware of something that you have already figured out.  So being able to review our design and compare it to SwiftAI would be great.

See you on Discord
Peter
