### ISSUE TITLE
MIT vs Apache license

### ISSUE THREAD

**Issue by freemin7** [FluxML/FastAI.jl#8]
FastAI seems to be under a apache license, not sure you can port it and license it under MIT.

**Comment by ToucheSir** [comment]
Given the project is still in its early stages and has received the blessing of fast.ai's creator, I don't see any issues with the current licensing arrangement. Moreover, this is meant to be a "re-imagining" of the Python codebase in Julia rather than a transliterated fork (the APIs have diverged from the beginning, to say nothing of the implementations) :slightly_smiling_face:

**Comment by freemin7** [comment]
Then have you done everything right, as far as i can tell. But IANAL
